# Generated by Django 3.1 on 2020-09-28 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASEGURADORA',
            fields=[
                ('id_aseguradora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BANCO',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DATO_PAGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_corriente', models.CharField(max_length=30)),
                ('id_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.banco')),
            ],
        ),
        migrations.CreateModel(
            name='EMPRESA',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('contacto', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ESTADO_CONTRATO',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ESTADO_POLIZA',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ESTADO_PROCESO_VENTA',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ESTADO_SOLICITUD',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ESTADO_SUBASTA',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FORMA_PAGO',
            fields=[
                ('id_forma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_forma', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PAIS',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('iso', models.CharField(max_length=2)),
                ('nombre_pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PERSONA',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=11, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('codigo_activacion', models.IntegerField(blank=True, null=True)),
                ('id_empresa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
        ),
        migrations.CreateModel(
            name='POSTULACION_PRODUCTO',
            fields=[
                ('id_postulacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PROCESO_VENTA',
            fields=[
                ('id_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado_proceso_venta')),
                ('id_postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postulacion_producto')),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_CONTRATO',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_PAGO',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_PERSONA',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_PROCESO_VENTA',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TRANSPORTE',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('refrigeracion', models.CharField(max_length=2)),
                ('tamanio', models.CharField(max_length=30)),
                ('capacidad_carga', models.FloatField()),
                ('direccion_origen', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateField()),
                ('adicional', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SUBASTA_TRANSPORTE',
            fields=[
                ('id_subasta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado_subasta')),
                ('id_proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.proceso_venta')),
                ('id_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transporte')),
            ],
        ),
        migrations.CreateModel(
            name='SOLICITUD_COMPRA',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('direccion_destino', models.CharField(max_length=100)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado_solicitud')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SEGURO',
            fields=[
                ('id_seguro', models.AutoField(primary_key=True, serialize=False)),
                ('poliza', models.CharField(max_length=35)),
                ('fecha_actualizacion', models.DateField()),
                ('id_aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aseguradora')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado_poliza')),
                ('id_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
        migrations.AddField(
            model_name='proceso_venta',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitud_compra'),
        ),
        migrations.AddField(
            model_name='proceso_venta',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_proceso_venta'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipo_persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PAGO',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('id_dato_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dato_pago')),
                ('id_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proceso_venta')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_pago')),
            ],
        ),
        migrations.CreateModel(
            name='HISTORiAL_SUBASTA',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('oferta', models.IntegerField()),
                ('fecha_oferta', models.DateTimeField()),
                ('id_subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subasta_transporte')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais'),
        ),
        migrations.CreateModel(
            name='DETALLE_SOLICITUD',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitud_compra')),
            ],
        ),
        migrations.CreateModel(
            name='DETALLE_POSTULACION',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha_elaboracion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('id_postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postulacion_producto')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.AddField(
            model_name='dato_pago',
            name='id_forma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forma_pago'),
        ),
        migrations.AddField(
            model_name='dato_pago',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona'),
        ),
        migrations.CreateModel(
            name='CONTRATO',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('contrato', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado_contrato')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_contrato')),
            ],
        ),
        migrations.CreateModel(
            name='BODEGA',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('id_postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postulacion_producto')),
            ],
        ),
        migrations.AddField(
            model_name='aseguradora',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais'),
        ),
    ]
